"""add_users_table

Revision ID: 295d45358817
Revises:
Create Date: 2025-05-20 00:04:21.387591

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "295d45358817"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.String(length=20), nullable=False),
        sa.Column("username", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=11), nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_users_phone"), ["phone"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_phone"))
        batch_op.drop_index(batch_op.f("ix_users_id"))

    op.drop_table("users")
    # ### end Alembic commands ###
