"""add_logs_table

Revision ID: 4018509c0ce4
Revises: 295d45358817
Create Date: 2025-05-20 00:43:03.890030

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4018509c0ce4"
down_revision = "295d45358817"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("endpoint", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_logs_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_logs_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_logs_user_id"))
        batch_op.drop_index(batch_op.f("ix_logs_id"))

    op.drop_table("logs")
    # ### end Alembic commands ###
